/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package latihan12;

import com.toedter.calendar.JDateChooser;

import javax.swing.JTable;

import java.sql.Connection;

import java.sql.DriverManager;

import java.sql.ResultSet;

import java.sql.ResultSetMetaData;

import java.sql.Statement;

import java.util.logging.Level;

import javax.swing.table.DefaultTableModel;

import java.text.DateFormat;

import java.text.SimpleDateFormat;

import java.util.Calendar;

import java.sql.*;

import java.util.Date;

import java.util.*;

import java.util.Locale;

import java.util.Vector;

import javax.swing.JOptionPane;

/**
 *
 * @author steven
 */
public class FrameInputUpdate9 extends javax.swing.JFrame {

    /**
     * Creates new form FrameInputUpdate9
     */
    public FrameInputUpdate9() {
        initComponents();

        Connection koneksi = null;

        Statement stmt = null;

        String query = "SELECT idpengguna,namalengkap,namapengguna,katakunci,tanggalmulai,tanggalberakhir FROM pengguna";

        String url = "jdbc:postgresql://localhost:5432/pdam";

        String user = "steven";

        String password = "kucing";

        try {

            koneksi = DriverManager.getConnection(url, user, password);

            stmt = koneksi.createStatement();

            ResultSet rs = stmt.executeQuery(query);

            ResultSetMetaData rsmd = rs.getMetaData();

            Vector<Vector> coba2 = new Vector<Vector>();

            while (rs.next()) {

                DateFormat terformat1 = new SimpleDateFormat("EEEE, dd MMMM yyyy");

                Date tanggalMulai = rs.getDate("tanggalmulai");

                Date tanggalBerakhir = rs.getDate("tanggalberakhir");

                String tanggal1 = terformat1.format(tanggalMulai);

                String tanggal2 = terformat1.format(tanggalBerakhir);

                Vector<String> isiBaris = new Vector<String>();

                isiBaris.add(rs.getString("idpengguna"));

                isiBaris.add(rs.getString("namalengkap"));

                isiBaris.add(rs.getString("namapengguna"));

                isiBaris.add(rs.getString("katakunci"));

                isiBaris.add(tanggal1);

                isiBaris.add(tanggal2);

                coba2.add(isiBaris);

                Vector<String> namaKolom = new Vector<String>();

                namaKolom.addElement(rsmd.getColumnLabel(1));

                namaKolom.addElement(rsmd.getColumnLabel(2));

                namaKolom.addElement(rsmd.getColumnLabel(3));

                namaKolom.addElement(rsmd.getColumnLabel(4));

                namaKolom.addElement(rsmd.getColumnLabel(5));

                namaKolom.addElement(rsmd.getColumnLabel(6));

                DefaultTableModel tabel1 = new DefaultTableModel(coba2, namaKolom);

                jTable1.setModel(tabel1);

                koneksi.close();

            }

        } catch (SQLException ex) {

            ex.printStackTrace();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jLabel1.setText("ID Pengguna");

        jTextField1.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jTextField1.setEnabled(false);

        jLabel2.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jLabel2.setText("Nama Lengkap");

        jTextField2.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jLabel3.setText("Nama Pengguna");

        jTextField3.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jLabel4.setText("Kata Kunci");

        jTextField4.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jLabel5.setText("Tanggal Mulai");

        jDateChooser1.setDateFormatString("EEEE, dd MMMM yyyy");
        jDateChooser1.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jLabel6.setText("Tanggal Berakhir");

        jDateChooser2.setDateFormatString("EEEE, dd MMMM yyyy");
        jDateChooser2.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N

        jButton1.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jButton1.setText("Simpan");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jButton2.setText("Edit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jButton3.setText("Simpan Ulang");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton4.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jButton4.setText("Hapus");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jButton5.setText("Cetak Laporan");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 781, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(jDateChooser2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField4)
                                    .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextField3)
                                    .addComponent(jTextField1)
                                    .addComponent(jTextField2))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(2, 2, 2)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6))
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        String namaLengkap = jTextField2.getText();

        String namaPengguna = jTextField3.getText();

        String kataKunci = jTextField4.getText();

        java.sql.Date tanggalMulai = new java.sql.Date(jDateChooser1.getDate().getTime());

        java.sql.Date tanggalBerakhir = new java.sql.Date(jDateChooser2.getDate().getTime());

        Connection koneksi = null;

        Statement stmt = null;

        PreparedStatement PSInsert = null;

        String query = "SELECT idpengguna,namalengkap,namapengguna,katakunci,tanggalmulai,tanggalberakhir FROM pengguna";

        String masukanData = "INSERT INTO pengguna" + "(namalengkap,namapengguna,katakunci,tanggalmulai,tanggalberakhir)VALUES" + "(?,?,?,?,?)";

        String url = "jdbc:postgresql://localhost:5432/pdam";

        String user = "steven";

        String password = "kucing";

        try {

            koneksi = DriverManager.getConnection(url, user, password);

            PSInsert = koneksi.prepareStatement(masukanData);

            PSInsert.setString(1, namaLengkap);

            PSInsert.setString(2, namaPengguna);

            PSInsert.setString(3, kataKunci);

            PSInsert.setDate(4, tanggalMulai);

            PSInsert.setDate(5, tanggalBerakhir);

            PSInsert.executeUpdate();

            stmt = koneksi.createStatement();

            ResultSet rs = stmt.executeQuery(query);

            ResultSetMetaData rsmd = rs.getMetaData();

            Vector<Vector> coba2 = new Vector<Vector>();

            while (rs.next()) {

                DateFormat terformat1 = new SimpleDateFormat("EEEE, dd MMMM yyyy");

                Date tanggalMulai2 = rs.getDate("tanggalmulai");

                String tanggalMulai3 = terformat1.format(tanggalMulai2);

                Date tanggalBerakhir2 = rs.getDate("tanggalberakhir");

                String tanggalBerakhir3 = terformat1.format(tanggalBerakhir2);

                Vector<String> isiBaris = new Vector<String>();

                isiBaris.add(rs.getString("idpengguna"));

                isiBaris.add(rs.getString("namalengkap"));

                isiBaris.add(rs.getString("namapengguna"));

                isiBaris.add(rs.getString("katakunci"));

                isiBaris.add(tanggalMulai3);

                isiBaris.add(tanggalBerakhir3);

                coba2.add(isiBaris);

                Vector<String> namaKolom = new Vector<String>();

                namaKolom.addElement(rsmd.getColumnLabel(1));

                namaKolom.addElement(rsmd.getColumnLabel(2));

                namaKolom.addElement(rsmd.getColumnLabel(3));

                namaKolom.addElement(rsmd.getColumnLabel(4));

                namaKolom.addElement(rsmd.getColumnLabel(5));

                namaKolom.addElement(rsmd.getColumnLabel(6));

                DefaultTableModel tabel1 = new DefaultTableModel(coba2, namaKolom);

                jTable1.setModel(tabel1);

                koneksi.close();

                jTextField1.setText("");

                jTextField2.setText("");

                jTextField3.setText("");

                jTextField4.setText("");

                jDateChooser1.setDate(null);

                jDateChooser2.setDate(null);

            }

        } catch (SQLException ex) {

            ex.printStackTrace();

        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        try {

            DefaultTableModel tm = (DefaultTableModel) jTable1.getModel();

            int editData = jTable1.getSelectedRow();

            jTextField1.setText(tm.getValueAt(editData, 0).toString());

            jTextField2.setText(tm.getValueAt(editData, 1).toString());

            jTextField3.setText(tm.getValueAt(editData, 2).toString());

            jTextField4.setText(tm.getValueAt(editData, 3).toString());

            DateFormat terformat1 = new SimpleDateFormat("EEEE, dd MMMM yyyy");

            String tanggalMulai1 = tm.getValueAt(editData, 4).toString();

            String tanggalBerakhir1 = tm.getValueAt(editData, 5).toString();

            Date tanggalMulai2 = terformat1.parse(tanggalMulai1);

            Date tanggalBerakhir2 = terformat1.parse(tanggalBerakhir1);

            jDateChooser1.setDate(tanggalMulai2);

            jDateChooser2.setDate(tanggalBerakhir2);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error: " + ex);

        }


    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:

        String idTanggal = jTextField1.getText();

        Integer idTanggal2 = Integer.valueOf(idTanggal);

        String namaLengkap = jTextField2.getText();

        String namaPengguna = jTextField3.getText();

        String kataKunci = jTextField4.getText();

        java.sql.Date tanggalMulai = new java.sql.Date(jDateChooser1.getDate().getTime());

        java.sql.Date tanggalBerakhir = new java.sql.Date(jDateChooser2.getDate().getTime());

        Connection koneksi = null;

        Statement stmt = null;

        PreparedStatement PSUpdate = null;

        String query = "SELECT idpengguna,namalengkap,namapengguna,katakunci,tanggalmulai,tanggalberakhir FROM pengguna";

        String updateData = "UPDATE pengguna SET namalengkap = ?, namapengguna = ?, katakunci = ?, tanggalmulai = ?, tanggalberakhir = ? WHERE idpengguna = ?";

        String url = "jdbc:postgresql://localhost:5432/pdam";

        String user = "steven";

        String password = "kucing";

        try {

            koneksi = DriverManager.getConnection(url, user, password);

            PSUpdate = koneksi.prepareStatement(updateData);

            PSUpdate.setString(1, namaLengkap);

            PSUpdate.setString(2, namaPengguna);

            PSUpdate.setString(3, kataKunci);

            PSUpdate.setDate(4, tanggalMulai);

            PSUpdate.setDate(5, tanggalBerakhir);

            PSUpdate.setInt(6, idTanggal2);

            PSUpdate.executeUpdate();

            stmt = koneksi.createStatement();

            ResultSet rs = stmt.executeQuery(query);

            ResultSetMetaData rsmd = rs.getMetaData();

            Vector<Vector> coba2 = new Vector<Vector>();

            while (rs.next()) {

                DateFormat terformat1 = new SimpleDateFormat("EEEE, dd MMMM yyyy");

                Date tanggalMulai2 = rs.getDate("tanggalmulai");

                String tanggalMulai3 = terformat1.format(tanggalMulai2);

                Date tanggalBerakhir2 = rs.getDate("tanggalberakhir");

                String tanggalBerakhir3 = terformat1.format(tanggalBerakhir2);

                Vector<String> isiBaris = new Vector<String>();

                isiBaris.add(rs.getString("idpengguna"));

                isiBaris.add(rs.getString("namalengkap"));

                isiBaris.add(rs.getString("namapengguna"));

                isiBaris.add(rs.getString("katakunci"));

                isiBaris.add(tanggalMulai3);

                isiBaris.add(tanggalBerakhir3);

                coba2.add(isiBaris);

                Vector<String> namaKolom = new Vector<String>();

                namaKolom.addElement(rsmd.getColumnLabel(1));

                namaKolom.addElement(rsmd.getColumnLabel(2));

                namaKolom.addElement(rsmd.getColumnLabel(3));

                namaKolom.addElement(rsmd.getColumnLabel(4));

                namaKolom.addElement(rsmd.getColumnLabel(5));

                namaKolom.addElement(rsmd.getColumnLabel(6));

                DefaultTableModel tabel1 = new DefaultTableModel(coba2, namaKolom);

                jTable1.setModel(tabel1);

                koneksi.close();

                jTextField1.setText("");

                jTextField2.setText("");

                jTextField3.setText("");

                jTextField4.setText("");

                jDateChooser1.setDate(null);

                jDateChooser2.setDate(null);

            }

        } catch (SQLException ex) {

            ex.printStackTrace();

        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:

        String idPengguna = jTextField1.getText();

        Integer idPengguna2 = Integer.valueOf(idPengguna);

        String namaLengkap = jTextField2.getText();

        String namaPengguna = jTextField3.getText();

        String kataKunci = jTextField4.getText();

        java.sql.Date tanggalMulai = new java.sql.Date(jDateChooser1.getDate().getTime());

        java.sql.Date tanggalBerakhir = new java.sql.Date(jDateChooser2.getDate().getTime());

        Connection koneksi = null;

        Statement stmt = null;

        PreparedStatement PSHapus = null;

        String query = "SELECT idpengguna,namalengkap,namapengguna,katakunci,tanggalmulai,tanggalberakhir FROM pengguna";

        String hapusData = "DELETE FROM pengguna WHERE idpengguna = ?";

        String url = "jdbc:postgresql://localhost:5432/pdam";

        String user = "steven";

        String password = "kucing";

        try {

            koneksi = DriverManager.getConnection(url, user, password);

            PSHapus = koneksi.prepareStatement(hapusData);

            PSHapus.setInt(1, idPengguna2);

            PSHapus.executeUpdate();

            stmt = koneksi.createStatement();

            ResultSet rs = stmt.executeQuery(query);

            ResultSetMetaData rsmd = rs.getMetaData();

            Vector<Vector> coba2 = new Vector<Vector>();

            while (rs.next()) {

                DateFormat terformat1 = new SimpleDateFormat("EEEE, dd MMMM yyyy");

                Date tanggalMulai2 = rs.getDate("tanggalmulai");

                String tanggalMulai3 = terformat1.format(tanggalMulai2);

                Date tanggalBerakhir2 = rs.getDate("tanggalberakhir");

                String tanggalBerakhir3 = terformat1.format(tanggalBerakhir2);

                Vector<String> isiBaris = new Vector<String>();

                isiBaris.add(rs.getString("idpengguna"));

                isiBaris.add(rs.getString("namalengkap"));

                isiBaris.add(rs.getString("namapengguna"));

                isiBaris.add(rs.getString("katakunci"));

                isiBaris.add(tanggalMulai3);

                isiBaris.add(tanggalBerakhir3);

                coba2.add(isiBaris);

                Vector<String> namaKolom = new Vector<String>();

                namaKolom.addElement(rsmd.getColumnLabel(1));

                namaKolom.addElement(rsmd.getColumnLabel(2));

                namaKolom.addElement(rsmd.getColumnLabel(3));

                namaKolom.addElement(rsmd.getColumnLabel(4));

                namaKolom.addElement(rsmd.getColumnLabel(5));

                namaKolom.addElement(rsmd.getColumnLabel(6));

                DefaultTableModel tabel1 = new DefaultTableModel(coba2, namaKolom);

                jTable1.setModel(tabel1);

                koneksi.close();

                jTextField1.setText("");

                jTextField2.setText("");

                jTextField3.setText("");

                jTextField4.setText("");

                jDateChooser1.setDate(null);

                jDateChooser2.setDate(null);

            }

        } catch (SQLException ex) {

            ex.printStackTrace();

        }


    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameInputUpdate9.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameInputUpdate9.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameInputUpdate9.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameInputUpdate9.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameInputUpdate9().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
